### PR TITLE
Funhouse

### PR DESCRIPTION
**Pull request by ladyada**
two demos!

### CODE REVIEW

**Comment by ladyada** [comment]
@PaintYourDragon

**Comment by ladyada** [comment]
@brentru tryyyyyyyyy it

**Comment by brentru** [comment]
@ladyada  Ok, tried out both examples. The gauge widget is 🧈 'y smooth.. btw - TFT rotation on `hello_funhouse.ino` seems incorrect, text is upside down. I can PR.

**Comment by ladyada** [comment]
oh yeah probably just forgot to fix, please PR and maybe make a widget demo
anything is buttery smooth when you have triple buffering :D

**Pull request merged**
