### PR TITLE
Improvements for usage with ESP32-x 

### PR DESCRIPTION
**Pull request by brentru**
This pull request adds fixes and improvements for using this library with ESP32-x:
* Fix for hangs and freezes when using a sketch with LVGL and WiFi
  * The LVGL task is now pinned to core1, leaving core0 for WiFi. 
    * NOTE: On the unicore ESP32-C3, it is pinned to the available core.
* Fix for crashes when using LVGL with WiFi and TLS/SSL (mbedtls in esp32 core) by reducing memory usage
  * LVGL_Glue on ESP32 uses `ps_alloc()` instead of `malloc()` to allocate memory from PSRAM. Some functions such as `lv_tick_handler` are also placed into PSRAM.

### CODE REVIEW

**Comment by brentru** [comment]
@PaintYourDragon This is ready for review. Do you think I should also include/rewrite the FunHouse ESP32-S2 example to use the lock/unlock functionality? I'm not sure I need to, that example doesn't utilize wifi.

**Review by PaintYourDragon — APPROVED** [review]

**Comment by PaintYourDragon** [comment]
Regarding FunHouse: although not using WiFi, it would be nice to have an example showing/documenting what the lock/unlock functions are for and how they’re used. Thx!

**Comment by brentru** [comment]
I'll add those today prior to pulling in.

**Comment by brentru** [comment]
@PaintYourDragon  I've added an example, `examples/hello_funhouse_wifi/hello_funhouse_wifi.ino`, that shows how to use WiFi and LVGL together (using the modifications to LVGL_Glue proposed by this PR).

I'll merge when passing

**Pull request merged**
